#!/bin/bash

REGEX_ISSUE_ID="^(#[0-9]+|Merge|hotfix)"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
    echo "[commit-msg-hook] Your commit message is illegal. Please amend your commit to include the issue number ('#1')"
    exit 1
fi
