name: Gradle Build

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

permissions: write-all

env:
  IMAGE_NAME: bet-mates-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build --no-daemon

  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry (1)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: docker build --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg JWT_SECRET=$JWT_SECRET .

      - name: Login to GitHub Container Registry (2)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "1.0.${{ github.run_number }}")
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest

  acceptance:
    if: ${{ false }} # disabled due to github (free) token limitations
    name: Acceptance Tests
    needs: docker
    runs-on: ubuntu-latest
    permissions: write-all

    services:
      backend:
        image: ghcr.io/${{ github.repository_owner }}/bet-mates-core:latest
        ports:
          - 8080:8080
      frontend:
        image: ghcr.io/${{ github.repository_owner }}/bet-mates-web:latest
        ports:
          - 8000:80

    steps:
      - name: Checkout web
        uses: actions/checkout@v3
        with:
          repository: 'bet-mates/bet-mates-web'
          ref: 'main'
          token: ${{ secrets.PAT }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Run Acceptance Tests
        run: CYPRESS_BASE_URL=http://localhost:8000 pnpm cypress run
